### ISSUE TITLE
Plugin not loaded properly with VS2022+Flax 1.7 (expected to be compatible)

### ISSUE THREAD

**Issue by PascalSoftwares** [GoaLitiuM/RmlUi#21]
Added plugin to a clean new project (fresh installed engine v1.7 - couldn't use v1.6 due to VC++ 2022 complier issue)

Opening project shows following error:

```
---------------------------
Failed to compile scripts
---------------------------
Scripts compilation failed. Cannot load scene without game script modules. Please fix the compilation issues. See logs for more info.
 ---------------------------
```

And scene loaded broken.

Log trace shows following:

```
[ 00:00:07.145 ]: [Info] 1:\RmlUITest\Plugins\RmlUi
[ 00:00:07.639 ]: [Info] C:\Program Files (x86)\Flax\Flax_1.7\Source\Engine\Render2D\IncludeFreeType.h(7): fatal error C1083: bugger.dll Files\Microsoft Visual Studio 2022 Enterprise\VC\Tools\M
[ 00:00:07.655 ]: [Info] Task C:\Program Files\Microsoft Visual Studio 2022 Enterprise\VC\Tools\MSVC\14.37.32822\bin\HostX64\x64\cl.exe /nologo /c /std:c++14 /Oi /Gy /analyze- /Zc:inline /Ot /Ob2 /Zi /Zo /Ox /Oi /Oy /FC /errorReport:prompt /EHsc /GF /MD /fp:fast /fp:except- /GS /GR /WX- /W3 /wd"4005" /Zc:wchar_t /D "PLATFORM_WIN32" /D "WIN32" /D "_CRT_SECURE_NO_DEPRECATE" /D "_CRT_SECURE_NO_WARNINGS" /D "_WINDOWS" /D "WIN64" /D "PLATFORM_WINDOWS" /D "UNICODE" /D "_UNICODE" /D "USE_EDITOR" /D "BUILD_DEVELOPMENT" /D "NDEBUG" /D "FLAX_1" /D "FLAX_1_7" /D "FLAX_1_1_OR_NEWER" /D "FLAX_1_2_OR_NEWER" /D "FLAX_1_3_OR_NEWER" /D "FLAX_1_4_OR_NEWER" /D "FLAX_1_5_OR_NEWER" /D "FLAX_1_6_OR_NEWER" /D "FLAX_1_7_OR_NEWER" /D "RMLUI_API=__declspec(dllexport)" /D "FLAXENGINE_API=__declspec(dllimport)" /D "COMPILE_WITH_PROFILER" /D "TRACY_ENABLE" /D "TRACY_ON_DEMAND" /D "COMPILE_WITH_DEBUG_DRAW" /D "COMPILE_WITH_SHADER_CACHE_MANAGER" /D "COMPILE_WITH_MODEL_TOOL" /D "COMPILE_WITH_SHADER_COMPILER" /D "COMPILE_WITH_CSG_BUILDER" /D "COMPILE_WITH_NAV_MESH_BUILDER" /D "COMPILE_WITH_NETWORKING" /D "COMPILE_WITH_PHYSICS_COOKING" /D "COMPILE_WITH_PARTICLE_GPU_GRAPH" /D "COMPILE_WITH_GPU_PARTICLES" /D "COMPILE_WITH_ASSETS_IMPORTER" /D "COMPILE_WITH_MATERIAL_GRAPH" /D "COMPILE_WITH_AUDIO_TOOL" /D "COMPILE_WITH_OGG_VORBIS" /D "COMPILE_WITH_TEXTURE_TOOL" /I"C:\Program Files\Microsoft Visual Studio 2022 Enterprise\VC\Tools\MSVC\14.37.32822\include" /I"C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" /I"C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" /I"C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" /I"C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" /I"C:\Program Files (x86)\Flax\Flax_1.7\Source\ThirdParty" /IY:\RmlUITest\Plugins\RmlUi\Source /I"C:\Program Files (x86)\Flax\Flax_1.7\Source" /IY:\RmlUITest\Plugins\RmlUi\Source\RmlUi /IY:\RmlUITest\Plugins\RmlUi\Source\RmlUi\..\ThirdParty\RmlUi /I"C:\Program Files (x86)\Flax\Flax_1.7\Source\ThirdParty\freetype" /Fd"Y:\RmlUITest\Plugins\RmlUi\Cache/Intermediate\RmlUiEditorTarget\Windows\x64\Development\RmlUi\FlaxFontEngineInterface.pdb" /Fo"Y:\RmlUITest\Plugins\RmlUi\Cache/Intermediate\RmlUiEditorTarget\Windows\x64\Development\RmlUi\FlaxFontEngineInterface.obj" "Y:\RmlUITest\Plugins\RmlUi\Source\RmlUi\Flax\FlaxFontEngineInterface.cpp" failed with exit code 2
 
[ 00:00:07.696 ]: [Info] C:\Program Files (x86)\Flax\Flax_1.7\Source\Engine\Graphics\RenderView.h(1): warning C4819: HostX64\x64\cl.exe /nologo /c /std:c++14 /Oi /Gy /analyze- /Zc:inline /Ot /Ob2 /Zi /Zo /Ox /Oi /Oy /FC /errorReport:prompt /EHsc /GF /MD /fp:fa
[ 00:00:07.805 ]: [Info] C:\Program Files (x86)\Flax\Flax_1.7\Source\Engine\Graphics\RenderView.h(1): warning C4819: HostX64\x64\cl.exe /nologo /c /std:c++14 /Oi /Gy /analyze- /Zc:inline /Ot /Ob2 /Zi /Zo /Ox /Oi /Oy /FC /errorReport:prompt /EHsc /GF /MD /fp:fa
[ 00:00:09.211 ]: [Info] 2 tasks failed
[ 00:00:09.215 ]: [Info] Exception: Failed to build target RmlUiEditorTarget. See log.
Stack trace: 
[ 00:00:09.224 ]: [Info]    at Flax.Build.Builder.BuildTargetReferenceNativeCpp(Dictionary`2 buildContext, BuildData buildData, Reference reference) in F:\FlaxEngine\Source\Tools\Flax.Build\Build\NativeCpp\Builder.NativeCpp.cs:line 631
   at Flax.Build.Builder.BuildTargetNativeCpp(RulesAssembly rules, TaskGraph graph, Target target, Dictionary`2 buildContext, Toolchain toolchain, TargetConfiguration configuration, Boolean isBuildingReference, Boolean skipBuild) in F:\FlaxEngine\Source\Tools\Flax.Build\Build\NativeCpp\Builder.NativeCpp.cs:line 764
   at Flax.Build.Builder.BuildTargets() in F:\FlaxEngine\Source\Tools\Flax.Build\Build\Builder.cs:line 371
   at Flax.Build.Program.Main() in F:\FlaxEngine\Source\Tools\Flax.Build\Program.cs:line 150
Total time: 00:00:04.0613974 
[ 00:00:09.232 ]: [Error] Failed to run build tool, result: 1
```

Using VS 2022 and expected to compatible with RmlUI plugin at Flax 1.7 but it seems troublesome... is there anything I can do for fix?

**Comment by PascalSoftwares** [comment]
.sln file -> RmlUi vcxproj -> build gave me this error (IDK but message locale is all broken)

`Error C1083	���� ������ �� �� �����ϴ�. 'ft2build.h': No such file or directory	RmlUi (Plugins\RmlUi\RmlUi)	C:\Program Files (x86)\Flax\Flax_1.7\Source\Engine\Render2D\IncludeFreeType.`

At least I couldn't find _**ft2build.h**_ inside plugin or FlaxEngine installation or Windows SDK installation.... Maybe because of this?

**Comment by GoaLitiuM** [comment]
Seems to be related to #8
